[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle React Router - this MUST be the last redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
